"""
payload_loader.py

Thread-safe loader for the JSONL test datasets generated by
generate_test_payloads.py.

Supports sequential iteration (Scenario 1), random by category (Scenario 2),
and weighted-mix across multiple files (Scenario 3).
"""

from __future__ import annotations

import json
import random
import threading
from collections import defaultdict
from pathlib import Path
from typing import Sequence


CATEGORIES = ["simple", "medium", "complex", "extreme"]

# Default distribution mirrors the dataset composition.
DEFAULT_DIST = {"simple": 0.60, "medium": 0.25, "complex": 0.10, "extreme": 0.05}


class PayloadLoader:
    """Loads one or more JSONL files and serves payloads concurrently."""

    def __init__(
        self,
        *paths: str | Path,
        seed: int = 42,
        weights: Sequence[float] | None = None,
    ) -> None:
        self._rng = random.Random(seed)
        self._lock = threading.Lock()

        file_pools: list[list[dict]] = []
        for p in paths:
            records = [
                json.loads(line)
                for line in Path(p).open(encoding="utf-8")
                if line.strip()
            ]
            file_pools.append(records)

        # If weights given, build a combined pool respecting those weights.
        if weights and len(weights) == len(file_pools):
            all_records: list[dict] = []
            total = sum(weights)
            base = min(len(fp) for fp in file_pools)
            for fp, w in zip(file_pools, weights):
                n = int(base * w / total)
                all_records.extend(self._rng.sample(fp, min(n, len(fp))))
        else:
            all_records = [r for fp in file_pools for r in fp]

        self._records = all_records

        self._by_cat: dict[str, list[dict]] = defaultdict(list)
        for r in self._records:
            self._by_cat[r["expected_category"]].append(r)

        # Sequential cursor for Scenario 1
        self._cursor = 0

    # ── properties ─────────────────────────────────────────────────────────────

    @property
    def total(self) -> int:
        return len(self._records)

    @property
    def categories(self) -> list[str]:
        return [c for c in CATEGORIES if c in self._by_cat]

    # ── access patterns ────────────────────────────────────────────────────────

    def pick_random(self) -> dict:
        with self._lock:
            return self._rng.choice(self._records)

    def pick_by_distribution(self, dist: dict[str, float] | None = None) -> dict:
        """Weighted pick by category. Falls back to uniform if category empty."""
        with self._lock:
            d = dist or DEFAULT_DIST
            cats = [c for c in d if c in self._by_cat]
            weights = [d[c] for c in cats]
            category = self._rng.choices(cats, weights=weights, k=1)[0]
            return self._rng.choice(self._by_cat[category])

    def next_sequential(self) -> dict | None:
        """Ordered iteration; returns None when all records are exhausted."""
        with self._lock:
            if self._cursor >= len(self._records):
                return None
            rec = self._records[self._cursor]
            self._cursor += 1
            return rec

    def reset(self) -> None:
        with self._lock:
            self._cursor = 0

    # ── payload builder ────────────────────────────────────────────────────────

    def to_chat_payload(self, record: dict, user_suffix: str = "") -> dict:
        """Return the POST /chat body for a record.

        Appends user_suffix to session_id so concurrent users don't share
        Firestore documents.
        """
        sid = record["session_id"]
        if user_suffix:
            sid = f"{sid}-{user_suffix}"
        return {"message": record["message"], "session_id": sid}
